define(function () {
    var allMunicipalities = [
        { label: 'Aberdeen Township', value: '1330' },
        { label: 'Absecon City', value: '0101' },
        { label: 'Alexandria Township', value: '1001' },
        { label: 'Allamuchy Township', value: '2101' },
        { label: 'Allendale Borough', value: '0201' },
        { label: 'Allenhurst Borough', value: '1301' },
        { label: 'Allentown Borough', value: '1302' },
        { label: 'Alloway Township', value: '1701' },
        { label: 'Alpha Borough', value: '2102' },
        { label: 'Alpine Borough', value: '0202' },
        { label: 'Andover Borough', value: '1901' },
        { label: 'Andover Township', value: '1902' },
        { label: 'Asbury Park City', value: '1303' },
        { label: 'Atlantic City', value: '0102' },
        { label: 'Atlantic Highlands Borough', value: '1304' },
        { label: 'Audubon Borough', value: '0401' },
        { label: 'Audubon Park Borough', value: '0402' },
        { label: 'Avalon Borough', value: '0501' },
        { label: 'Avon-By-The-Sea Borough', value: '1305' },
        { label: 'Barnegat Light Borough', value: '1501' },
        { label: 'Barnegat Township', value: '1533' },
        { label: 'Barrington Borough', value: '0403' },
        { label: 'Bass River Township', value: '0301' },
        { label: 'Bay Head Borough', value: '1502' },
        { label: 'Bayonne City', value: '0901' },
        { label: 'Beach Haven Borough', value: '1503' },
        { label: 'Beachwood Borough', value: '1504' },
        { label: 'Bedminster Township', value: '1801' },
        { label: 'Belleville Township', value: '0701' },
        { label: 'Bellmawr Borough', value: '0404' },
        { label: 'Belmar Borough', value: '1306' },
        { label: 'Belvidere Town', value: '2103' },
        { label: 'Bergenfield Borough', value: '0203' },
        { label: 'Berkeley Heights Township', value: '2001' },
        { label: 'Berkeley Township', value: '1505' },
        { label: 'Berlin Borough', value: '0405' },
        { label: 'Berlin Township', value: '0406' },
        { label: 'Bernards Township', value: '1802' },
        { label: 'Bernardsville Borough', value: '1803' },
        { label: 'Bethlehem Township', value: '1002' },
        { label: 'Beverly City', value: '0302' },
        { label: 'Blairstown Township', value: '2104' },
        { label: 'Bloomfield Township', value: '0702' },
        { label: 'Bloomingdale Borough', value: '1601' },
        { label: 'Bloomsbury Borough', value: '1003' },
        { label: 'Bogota Borough', value: '0204' },
        { label: 'Boonton Town', value: '1401' },
        { label: 'Boonton Township', value: '1402' },
        { label: 'Bordentown City', value: '0303' },
        { label: 'Bordentown Township', value: '0304' },
        { label: 'Bound Brook Borough', value: '1804' },
        { label: 'Bradley Beach Borough', value: '1307' },
        { label: 'Branchburg Township', value: '1805' },
        { label: 'Branchville Borough', value: '1903' },
        { label: 'Brick Township', value: '1506' },
        { label: 'Bridgeton City', value: '0601' },
        { label: 'Bridgewater Township', value: '1806' },
        { label: 'Brielle Borough', value: '1308' },
        { label: 'Brigantine City', value: '0103' },
        { label: 'Brooklawn Borough', value: '0407' },
        { label: 'Buena Borough', value: '0104' },
        { label: 'Buena Vista Township', value: '0105' },
        { label: 'Burlington City', value: '0305' },
        { label: 'Burlington Township', value: '0306' },
        { label: 'Butler Borough', value: '1403' },
        { label: 'Byram Township', value: '1904' },
        { label: 'Caldwell Borough', value: '0703' },
        { label: 'Califon Borough', value: '1004' },
        { label: 'Camden City', value: '0408' },
        { label: 'Cape May City', value: '0502' },
        { label: 'Cape May Point Borough', value: '0503' },
        { label: 'Carlstadt Borough', value: '0205' },
        { label: 'Carneys Point Township', value: '1713' },
        { label: 'Carteret Borough', value: '1201' },
        { label: 'Cedar Grove Township', value: '0704' },
        { label: 'Chatham Borough', value: '1404' },
        { label: 'Chatham Township', value: '1405' },
        { label: 'Cherry Hill Township', value: '0409' },
        { label: 'Chesilhurst Borough', value: '0410' },
        { label: 'Chester Borough', value: '1406' },
        { label: 'Chester Township', value: '1407' },
        { label: 'Chesterfield Township', value: '0307' },
        { label: 'Cinnaminson Township', value: '0308' },
        { label: 'Clark Township', value: '2002' },
        { label: 'Clayton Borough', value: '0801' },
        { label: 'Clementon Borough', value: '0411' },
        { label: 'Cliffside Park Borough', value: '0206' },
        { label: 'Clifton City', value: '1602' },
        { label: 'Clinton Town', value: '1005' },
        { label: 'Clinton Township', value: '1006' },
        { label: 'Closter Borough', value: '0207' },
        { label: 'Collingswood Borough', value: '0412' },
        { label: 'Colts Neck Township', value: '1309' },
        { label: 'Commercial Township', value: '0602' },
        { label: 'Corbin City', value: '0106' },
        { label: 'Cranbury Township', value: '1202' },
        { label: 'Cranford Township', value: '2003' },
        { label: 'Cresskill Borough', value: '0208' },
        { label: 'Deal Borough', value: '1310' },
        { label: 'Deerfield Township', value: '0603' },
        { label: 'Delanco Township', value: '0309' },
        { label: 'Delaware Township', value: '1007' },
        { label: 'Delran Township', value: '0310' },
        { label: 'Demarest Borough', value: '0209' },
        { label: 'Dennis Township', value: '0504' },
        { label: 'Denville Township', value: '1408' },
        { label: 'Deptford Township', value: '0802' },
        { label: 'Dover Town', value: '1409' },
        { label: 'Downe Township', value: '0604' },
        { label: 'Dumont Borough', value: '0210' },
        { label: 'Dunellen Borough', value: '1203' },
        { label: 'Eagleswood Township', value: '1508' },
        { label: 'East Amwell Township', value: '1008' },
        { label: 'East Brunswick Township', value: '1204' },
        { label: 'East Greenwich Township', value: '0803' },
        { label: 'East Hanover Township', value: '1410' },
        { label: 'East Newark Borough', value: '0902' },
        { label: 'East Orange City', value: '0705' },
        { label: 'East Rutherford Borough', value: '0212' },
        { label: 'East Windsor Township', value: '1101' },
        { label: 'Eastampton Township', value: '0311' },
        { label: 'Eatontown Borough', value: '1311' },
        { label: 'Edgewater Borough', value: '0213' },
        { label: 'Edgewater Park Township', value: '0312' },
        { label: 'Edison Township', value: '1205' },
        { label: 'Egg Harbor City', value: '0107' },
        { label: 'Egg Harbor Township', value: '0108' },
        { label: 'Elizabeth City', value: '2004' },
        { label: 'Elk Township', value: '0804' },
        { label: 'Elmer Borough', value: '1702' },
        { label: 'Elmwood Park Borough', value: '0211' },
        { label: 'ElsinBorough Township', value: '1703' },
        { label: 'Emerson Borough', value: '0214' },
        { label: 'Englewood City', value: '0215' },
        { label: 'Englewood Cliffs Borough', value: '0216' },
        { label: 'Englishtown Borough', value: '1312' },
        { label: 'Essex Fells Borough', value: '0706' },
        { label: 'Estell Manor City', value: '0109' },
        { label: 'Evesham Township', value: '0313' },
        { label: 'Ewing Township', value: '1102' },
        { label: 'Fair Haven Borough', value: '1313' },
        { label: 'Fair Lawn Borough', value: '0217' },
        { label: 'Fairfield Borough', value: '0707' },
        { label: 'Fairfield Township', value: '0605' },
        { label: 'Fairview Borough', value: '0218' },
        { label: 'Fanwood Borough', value: '2005' },
        { label: 'Far Hills Borough', value: '1807' },
        { label: 'Farmingdale Borough', value: '1314' },
        { label: 'FieldsBorough Borough', value: '0314' },
        { label: 'Flemington Borough', value: '1009' },
        { label: 'Florence Township', value: '0315' },
        { label: 'Florham Park Borough', value: '1411' },
        { label: 'Folsom Borough', value: '0110' },
        { label: 'Fort Lee Borough', value: '0219' },
        { label: 'Frankford Township', value: '1905' },
        { label: 'Franklin Borough', value: '1906' },
        { label: 'Franklin Lakes Borough', value: '0220' },
        { label: 'Franklin Township', value: '0805' },
        { label: 'Franklin Township', value: '1010' },
        { label: 'Franklin Township', value: '1808' },
        { label: 'Franklin Township', value: '2105' },
        { label: 'Fredon Township', value: '1907' },
        { label: 'Freehold Borough', value: '1315' },
        { label: 'Freehold Township', value: '1316' },
        { label: 'Frelinghuysen Township', value: '2106' },
        { label: 'Frenchtown Borough', value: '1011' },
        { label: 'Galloway Township', value: '0111' },
        { label: 'Garfield City', value: '0221' },
        { label: 'Garwood Borough', value: '2006' },
        { label: 'GibbsBorough Borough', value: '0413' },
        { label: 'GlassBorough Borough', value: '0806' },
        { label: 'Glen Gardner Borough', value: '1012' },
        { label: 'Glen Ridge Borough', value: '0708' },
        { label: 'Glen Rock Borough', value: '0222' },
        { label: 'Gloucester City', value: '0414' },
        { label: 'Gloucester Township', value: '0415' },
        { label: 'Green Brook Township', value: '1809' },
        { label: 'Green Township', value: '1908' },
        { label: 'Greenwich Township', value: '0606' },
        { label: 'Greenwich Township', value: '0807' },
        { label: 'Greenwich Township', value: '2107' },
        { label: 'Guttenberg Town', value: '0903' },
        { label: 'Hackensack City', value: '0223' },
        { label: 'Hackettstown Town', value: '2108' },
        { label: 'Haddon Heights Borough', value: '0418' },
        { label: 'Haddon Township', value: '0416' },
        { label: 'Haddonfield Borough', value: '0417' },
        { label: 'Hainesport Township', value: '0316' },
        { label: 'Haledon Borough', value: '1603' },
        { label: 'Hamburg Borough', value: '1909' },
        { label: 'Hamilton Township', value: '0112' },
        { label: 'Hamilton Township', value: '1103' },
        { label: 'Hammonton Town', value: '0113' },
        { label: 'Hampton Borough', value: '1013' },
        { label: 'Hampton Township', value: '1910' },
        { label: 'Hanover Township', value: '1412' },
        { label: 'Harding Township', value: '1413' },
        { label: 'Hardwick Township', value: '2109' },
        { label: 'Hardyston Township', value: '1911' },
        { label: 'Harmony Township', value: '2110' },
        { label: 'Harrington Park Borough', value: '0224' },
        { label: 'Harrison Town', value: '0904' },
        { label: 'Harrison Township', value: '0808' },
        { label: 'Harvey Cedars Borough', value: '1509' },
        { label: 'Hasbrouck Heights Borough', value: '0225' },
        { label: 'Haworth Borough', value: '0226' },
        { label: 'Hawthorne Borough', value: '1604' },
        { label: 'Hazlet Township', value: '1339' },
        { label: 'Helmetta Borough', value: '1206' },
        { label: 'High Bridge Borough', value: '1014' },
        { label: 'Highland Park Borough', value: '1207' },
        { label: 'Highlands Borough', value: '1317' },
        { label: 'Hightstown Borough', value: '1104' },
        { label: 'HillsBoroughugh Township', value: '1810' },
        { label: 'Hillsdale Borough', value: '0227' },
        { label: 'Hillside Township', value: '2007' },
        { label: 'Hi-Nella Borough', value: '0419' },
        { label: 'Ho Ho Kus Borough', value: '0228' },
        { label: 'Hoboken City', value: '0905' },
        { label: 'Holland Township', value: '1015' },
        { label: 'Holmdel Township', value: '1318' },
        { label: 'Hopatcong Borough', value: '1912' },
        { label: 'Hope Township', value: '2111' },
        { label: 'Hopewell Borough', value: '1105' },
        { label: 'Hopewell Township', value: '0607' },
        { label: 'Hopewell Township', value: '1106' },
        { label: 'Howell Township', value: '1319' },
        { label: 'Independence Township', value: '2112' },
        { label: 'Interlaken Borough', value: '1320' },
        { label: 'Irvington Township', value: '0709' },
        { label: 'Island Heights Borough', value: '1510' },
        { label: 'Jackson Township', value: '1511' },
        { label: 'Jamesburg Borough', value: '1208' },
        { label: 'Jefferson Township', value: '1414' },
        { label: 'Jersey City', value: '0906' },
        { label: 'Keansburg Borough', value: '1321' },
        { label: 'Kearny Town', value: '0907' },
        { label: 'Kenilworth Borough', value: '2008' },
        { label: 'Keyport Borough', value: '1322' },
        { label: 'Kingwood Township', value: '1016' },
        { label: 'Kinnelon Borough', value: '1415' },
        { label: 'Knowlton Township', value: '2113' },
        { label: 'Lacey Township', value: '1512' },
        { label: 'Lafayette Township', value: '1913' },
        { label: 'Lake Como Borough', value: '1347' },
        { label: 'Lakehurst Borough', value: '1513' },
        { label: 'Lakewood Township', value: '1514' },
        { label: 'Lambertville City', value: '1017' },
        { label: 'Laurel Springs Borough', value: '0420' },
        { label: 'Lavallette Borough', value: '1515' },
        { label: 'Lawnside Borough', value: '0421' },
        { label: 'Lawrence Township', value: '0608' },
        { label: 'Lawrence Township', value: '1107' },
        { label: 'Lebanon Borough', value: '1018' },
        { label: 'Lebanon Township', value: '1019' },
        { label: 'Leonia Borough', value: '0229' },
        { label: 'Liberty Township', value: '2114' },
        { label: 'Lincoln Park Borough', value: '1416' },
        { label: 'Linden City', value: '2009' },
        { label: 'Lindenwold Borough', value: '0422' },
        { label: 'Linwood City', value: '0114' },
        { label: 'Little Egg Harbor Township', value: '1516' },
        { label: 'Little Falls Township', value: '1605' },
        { label: 'Little Ferry Borough', value: '0230' },
        { label: 'Little Silver Borough', value: '1323' },
        { label: 'Livingston Township', value: '0710' },
        { label: 'Loch Arbour Village', value: '1324' },
        { label: 'Lodi Borough', value: '0231' },
        { label: 'Logan Township', value: '0809' },
        { label: 'Long Beach Township', value: '1517' },
        { label: 'Long Branch City', value: '1325' },
        { label: 'Longport Borough', value: '0115' },
        { label: 'Lopatcong Township', value: '2115' },
        { label: 'Lower Alloways Crk Township', value: '1704' },
        { label: 'Lower Township', value: '0505' },
        { label: 'Lumberton Township', value: '0317' },
        { label: 'Lyndhurst Township', value: '0232' },
        { label: 'Madison Borough', value: '1417' },
        { label: 'Magnolia Borough', value: '0423' },
        { label: 'Mahwah Township', value: '0233' },
        { label: 'Manalapan Township', value: '1326' },
        { label: 'Manasquan Borough', value: '1327' },
        { label: 'Manchester Township', value: '1518' },
        { label: 'Mannington Township', value: '1705' },
        { label: 'Mansfield Township', value: '0318' },
        { label: 'Mansfield Township', value: '2116' },
        { label: 'Mantoloking Borough', value: '1519' },
        { label: 'Mantua Township', value: '0810' },
        { label: 'Manville Borough', value: '1811' },
        { label: 'Maple Shade Township', value: '0319' },
        { label: 'Maplewood Township', value: '0711' },
        { label: 'Margate City', value: '0116' },
        { label: 'MarlBorough Township', value: '1328' },
        { label: 'Matawan Borough', value: '1329' },
        { label: 'Maurice River Township', value: '0609' },
        { label: 'Maywood Borough', value: '0234' },
        { label: 'Medford Lakes Borough', value: '0321' },
        { label: 'Medford Township', value: '0320' },
        { label: 'Mendham Borough', value: '1418' },
        { label: 'Mendham Township', value: '1419' },
        { label: 'Merchantville Borough', value: '0424' },
        { label: 'Metuchen Borough', value: '1210' },
        { label: 'Middle Township', value: '0506' },
        { label: 'Middlesex Borough', value: '1211' },
        { label: 'Middletown Township', value: '1331' },
        { label: 'Midland Park Borough', value: '0235' },
        { label: 'Milford Township', value: '1020' },
        { label: 'Millburn Township', value: '0712' },
        { label: 'Millstone Borough', value: '1812' },
        { label: 'Millstone Township', value: '1332' },
        { label: 'Milltown Borough', value: '1212' },
        { label: 'Millville City', value: '0610' },
        { label: 'Mine Hill Township', value: '1420' },
        { label: 'Monmouth Beach Borough', value: '1333' },
        { label: 'Monroe Township', value: '0811' },
        { label: 'Monroe Township', value: '1213' },
        { label: 'Montague Township', value: '1914' },
        { label: 'Montclair Township', value: '0713' },
        { label: 'Montgomery Township', value: '1813' },
        { label: 'Montvale Borough', value: '0236' },
        { label: 'Montville Township', value: '1421' },
        { label: 'Moonachie Borough', value: '0237' },
        { label: 'Moorestown Township', value: '0322' },
        { label: 'Morris Plains Borough', value: '1423' },
        { label: 'Morris Township', value: '1422' },
        { label: 'Morristown Town', value: '1424' },
        { label: 'Mount Arlington Borough', value: '1426' },
        { label: 'Mount Ephriam Borough', value: '0425' },
        { label: 'Mount Holly Township', value: '0323' },
        { label: 'Mount Laurel Township', value: '0324' },
        { label: 'Mount Olive Township', value: '1427' },
        { label: 'Mountain Lakes Borough', value: '1425' },
        { label: 'Mountainside Borough', value: '2010' },
        { label: 'Mullica Township', value: '0117' },
        { label: 'National Park Borough', value: '0812' },
        { label: 'Neptune City Borough', value: '1335' },
        { label: 'Neptune Township', value: '1334' },
        { label: 'Netcong Borough', value: '1428' },
        { label: 'New Brunswick City', value: '1214' },
        { label: 'New Hanover Township', value: '0325' },
        { label: 'New Milford Borough', value: '0238' },
        { label: 'New Providence Borough', value: '2011' },
        { label: 'Newark City', value: '0714' },
        { label: 'Newfield Borough', value: '0813' },
        { label: 'Newton Town', value: '1915' },
        { label: 'North Arlington Borough', value: '0239' },
        { label: 'North Bergen Township', value: '0908' },
        { label: 'North Brunswick Township', value: '1215' },
        { label: 'North Caldwell Borough', value: '0715' },
        { label: 'North Haledon Borough', value: '1606' },
        { label: 'North Hanover Township', value: '0326' },
        { label: 'North Plainfield Borough', value: '1814' },
        { label: 'North Wildwood City', value: '0507' },
        { label: 'Northfield City', value: '0118' },
        { label: 'Northvale Borough', value: '0240' },
        { label: 'Norwood Borough', value: '0241' },
        { label: 'Nutley Township', value: '0716' },
        { label: 'Oakland Borough', value: '0242' },
        { label: 'Oaklyn Borough', value: '0426' },
        { label: 'Ocean City', value: '0508' },
        { label: 'Ocean Gate Borough', value: '1521' },
        { label: 'Ocean Township', value: '1337' },
        { label: 'Ocean Township', value: '1520' },
        { label: 'Oceanport Borough', value: '1338' },
        { label: 'Ogdensburg Borough', value: '1916' },
        { label: 'Old Bridge Township', value: '1209' },
        { label: 'Old Tappan Borough', value: '0243' },
        { label: 'Oldmans Township', value: '1706' },
        { label: 'Oradell Borough', value: '0244' },
        { label: 'Orange City', value: '0717' },
        { label: 'Oxford Township', value: '2117' },
        { label: 'Pahaquarry Township', value: '2118' },
        { label: 'Palisades Park Borough', value: '0245' },
        { label: 'Palmyra Borough', value: '0327' },
        { label: 'Paramus Borough', value: '0246' },
        { label: 'Park Ridge Borough', value: '0247' },
        { label: 'Parsippany-Troy Hills', value: '1429' },
        { label: 'Passaic City', value: '1607' },
        { label: 'Passaic Township', value: '1430' },
        { label: 'Paterson City', value: '1608' },
        { label: 'PaulsBorough Borough', value: '0814' },
        { label: 'Peapack-Gladstone Borough', value: '1815' },
        { label: 'Pemberton Borough', value: '0328' },
        { label: 'Pemberton Township', value: '0329' },
        { label: 'Pennington Borough', value: '1108' },
        { label: 'Penns Grove Borough', value: '1707' },
        { label: 'Pennsauken Township', value: '0427' },
        { label: 'Pennsville Township', value: '1708' },
        { label: 'Pequannock Township', value: '1431' },
        { label: 'Perth Amboy City', value: '1216' },
        { label: 'Phillipsburg Town', value: '2119' },
        { label: 'Pilesgrove Township', value: '1709' },
        { label: 'Pine Beach Borough', value: '1522' },
        { label: 'Pine Hill Borough', value: '0428' },
        { label: 'Pine Valley Borough', value: '0429' },
        { label: 'Piscataway Township', value: '1217' },
        { label: 'Pitman Borough', value: '0815' },
        { label: 'Pittsgrove Township', value: '1710' },
        { label: 'Plainfield City', value: '2012' },
        { label: 'PlainsBorough Township', value: '1218' },
        { label: 'Pleasantville City', value: '0119' },
        { label: 'Plumsted Township', value: '1523' },
        { label: 'Pohatcong Township', value: '2120' },
        { label: 'Point Pleasant Borough', value: '1524' },
        { label: 'Pompton Lakes Borough', value: '1609' },
        { label: 'Port Republic City', value: '0120' },
        { label: 'Princeton', value: '1114' },
        { label: 'Princeton Borough', value: '1109' },
        { label: 'Princeton Township', value: '1110' },
        { label: 'Prospect Park Borough', value: '1610' },
        { label: 'Point Pleasant Beach Borough', value: '1525' },
        { label: 'Quinton Township', value: '1711' },
        { label: 'Rahway City', value: '2013' },
        { label: 'Ramsey Borough', value: '0248' },
        { label: 'Randolph Township', value: '1432' },
        { label: 'Raritan Borough', value: '1816' },
        { label: 'Raritan Township', value: '1021' },
        { label: 'Readington Township', value: '1022' },
        { label: 'Red Bank Borough', value: '1340' },
        { label: 'Ridgefield Borough', value: '0249' },
        { label: 'Ridgefield Park Village', value: '0250' },
        { label: 'Ridgewood Village', value: '0251' },
        { label: 'Ringwood Borough', value: '1611' },
        { label: 'River Edge Borough', value: '0252' },
        { label: 'River Vale Township', value: '0253' },
        { label: 'Riverdale Borough', value: '1433' },
        { label: 'Riverside Township', value: '0330' },
        { label: 'Riverton Borough', value: '0331' },
        { label: 'Robbinsville Township', value: '1112' },
        { label: 'Rochelle Park Township', value: '0254' },
        { label: 'Rockaway Borough', value: '1434' },
        { label: 'Rockaway Township', value: '1435' },
        { label: 'Rockleigh Borough', value: '0255' },
        { label: 'Rocky Hill Borough', value: '1817' },
        { label: 'Roosevelt Borough', value: '1341' },
        { label: 'Roseland Borough', value: '0718' },
        { label: 'Roselle Borough', value: '2014' },
        { label: 'Roselle Park Borough', value: '2015' },
        { label: 'Roxbury Township', value: '1436' },
        { label: 'Rumson Borough', value: '1342' },
        { label: 'Runnemede Borough', value: '0430' },
        { label: 'Rutherford Borough', value: '0256' },
        { label: 'Saddle Brook Township', value: '0257' },
        { label: 'Saddle River Borough', value: '0258' },
        { label: 'Salem City', value: '1712' },
        { label: 'Sandvston Township', value: '1917' },
        { label: 'Sayreville Borough', value: '1219' },
        { label: 'Scotch Plains Township', value: '2016' },
        { label: 'Sea Bright Borough', value: '1343' },
        { label: 'Sea Girt Borough', value: '1344' },
        { label: 'Sea Isle City', value: '0509' },
        { label: 'Seaside Heights Borough', value: '1526' },
        { label: 'Seaside Park Borough', value: '1527' },
        { label: 'Secaucus Town', value: '0909' },
        { label: 'Shamong Township', value: '0332' },
        { label: 'Shiloh Borough', value: '0611' },
        { label: 'Ship Bottom Borough', value: '1528' },
        { label: 'Shrewsbury Borough', value: '1345' },
        { label: 'Shrewsbury Township', value: '1346' },
        { label: 'Somerdale Borough', value: '0431' },
        { label: 'Somers Point City', value: '0121' },
        { label: 'Somerville Borough', value: '1818' },
        { label: 'South Amboy City', value: '1220' },
        { label: 'South Bound Brook Borough', value: '1819' },
        { label: 'South Brunswick Township', value: '1221' },
        { label: 'South Hackensack Township', value: '0259' },
        { label: 'South Harrison Township', value: '0816' },
        { label: 'South Orange Village Township', value: '0719' },
        { label: 'South Plainfield Borough', value: '1222' },
        { label: 'South River Borough', value: '1223' },
        { label: 'South Toms River Borough', value: '1529' },
        { label: 'Southampton Township', value: '0333' },
        { label: 'Sparta Township', value: '1918' },
        { label: 'Spotswood Borough', value: '1224' },
        { label: 'Spring Lake Borough', value: '1348' },
        { label: 'Spring Lake Heights Borough', value: '1349' },
        { label: 'Springfield Township', value: '0334' },
        { label: 'Springfield Township', value: '2017' },
        { label: 'Stafford Township', value: '1530' },
        { label: 'Stanhope Borough', value: '1919' },
        { label: 'Stillwater Township', value: '1920' },
        { label: 'Stockton Borough', value: '1023' },
        { label: 'Stone Harbor Borough', value: '0510' },
        { label: 'Stow Creek Township', value: '0612' },
        { label: 'Stratford Borough', value: '0432' },
        { label: 'Summit City', value: '2018' },
        { label: 'Surf City Borough', value: '1531' },
        { label: 'Sussex Borough', value: '1921' },
        { label: 'SwedesBorough Borough', value: '0817' },
        { label: 'Tabernacle Township', value: '0335' },
        { label: 'Tavistock Borough', value: '0433' },
        { label: 'Teaneck Township', value: '0260' },
        { label: 'Tenafly Borough', value: '0261' },
        { label: 'TeterBorough Borough', value: '0262' },
        { label: 'Tewksbury Township', value: '1024' },
        { label: 'Tinton Falls Borough', value: '1336' },
        { label: 'Toms River Township', value: '1507' },
        { label: 'Totowa Borough', value: '1612' },
        { label: 'Trenton City', value: '1111' },
        { label: 'Tuckerton Borough', value: '1532' },
        { label: 'Union Beach Borough', value: '1350' },
        { label: 'Union City', value: '0910' },
        { label: 'Union Township', value: '1025' },
        { label: 'Union Township', value: '2019' },
        { label: 'Upper Deerfield Township', value: '0613' },
        { label: 'Upper Freehold Township', value: '1351' },
        { label: 'Upper Pittsgrove Township', value: '1714' },
        { label: 'Upper Saddle River Borough', value: '0263' },
        { label: 'Upper Township', value: '0511' },
        { label: 'Ventnor City', value: '0122' },
        { label: 'Vernon Township', value: '1922' },
        { label: 'Verona Township', value: '0720' },
        { label: 'Victory Gardens Borough', value: '1437' },
        { label: 'Vineland City', value: '0614' },
        { label: 'Voorhees Township', value: '0434' },
        { label: 'Waldwick Borough', value: '0264' },
        { label: 'Wall Township', value: '1352' },
        { label: 'Wallington Borough', value: '0265' },
        { label: 'Walpack Township', value: '1923' },
        { label: 'Wanaque Borough', value: '1613' },
        { label: 'Wantage Township', value: '1924' },
        { label: 'Warren Township', value: '1820' },
        { label: 'Washington Borough', value: '2121' },
        { label: 'Washington Township', value: '0266' },
        { label: 'Washington Township', value: '0336' },
        { label: 'Washington Township', value: '0818' },
        { label: 'Washington Township', value: '1438' },
        { label: 'Washington Township', value: '2122' },
        { label: 'Watchung Borough', value: '1821' },
        { label: 'Waterford Township', value: '0435' },
        { label: 'Wayne Township', value: '1614' },
        { label: 'Weehawken Township', value: '0911' },
        { label: 'Wenonah Borough', value: '0819' },
        { label: 'West Amwell Township', value: '1026' },
        { label: 'West Caldwell Township', value: '0721' },
        { label: 'West Cape May Borough', value: '0512' },
        { label: 'West Deptford Township', value: '0820' },
        { label: 'West Long Branch Borough', value: '1353' },
        { label: 'West Milford Township', value: '1615' },
        { label: 'West New York Town', value: '0912' },
        { label: 'West Orange Township', value: '0722' },
        { label: 'West Wildwood Borough', value: '0513' },
        { label: 'West Windsor Township', value: '1113' },
        { label: 'Westampton Township', value: '0337' },
        { label: 'Westfield Town', value: '2020' },
        { label: 'Westville Borough', value: '0821' },
        { label: 'Westwood Borough', value: '0267' },
        { label: 'Weymouth Township', value: '0123' },
        { label: 'Wharton Borough', value: '1439' },
        { label: 'White Township', value: '2123' },
        { label: 'Wildwood City', value: '0514' },
        { label: 'Wildwood Crest Borough', value: '0515' },
        { label: 'WillingBorough Township', value: '0338' },
        { label: 'Winfield Township', value: '2021' },
        { label: 'Winslow Township', value: '0436' },
        { label: 'Woodbine Borough', value: '0516' },
        { label: 'Woodbridge Township', value: '1225' },
        { label: 'Woodbury City', value: '0822' },
        { label: 'Woodbury Heights Borough', value: '0823' },
        { label: 'Woodcliff Lake Borough', value: '0268' },
        { label: 'Woodland Park Borough', value: '1616' },
        { label: 'Woodland Township', value: '0339' },
        { label: 'Woodlynne Borough', value: '0437' },
        { label: 'Wood-Ridge Borough', value: '0269' },
        { label: 'Woodstown Borough', value: '1715' },
        { label: 'Woolwich Township', value: '0824' },
        { label: 'Wrightstown Borough', value: '0340' },
        { label: 'Wyckoff Township', value: '0270' }
    ];

    function getMunis() {
        return allMunicipalities;
    }

    function filterMunicipalities(countyCode) {
        let filteredMuni = allMunicipalities.filter(function (muni) {
            return muni.value.substring(0,2) === countyCode;
        });
        return filteredMuni;
    }
    
    function getMuniReadable(code) {
        const target = allMunicipalities.find(muni => muni.value === code);
        if (target) {
            return target.label;
        }
        return null;
    }

    return {
        getMunis: getMunis,
        filterMunicipalities: filterMunicipalities,
        getMuniReadable: getMuniReadable
    };
});